- name: "nginx_private - {{ project_name }} - PROJECT_DIR - Check LOCAL"
  stat:
    path: "/home/{{ruser}}/mempoule_private/{{ project_name }}"
  register: local_projectdir
  when: project_name is defined
  delegate_to: localhost

- name: "nginx_private - ENDPLAY: projectdir"
  meta: end_play
  when:
  - (project_name is defined and not local_projectdir.stat.exists) or not project_name is defined


- name: "nginx_private - {{ project_name }} - virtualhost.conf - Check LOCAL"
  stat:
    path: "/home/{{ruser}}/mempoule_private/{{ project_name }}/virtualhost.conf"
  register: local_virtualconf
  delegate_to: localhost

- name: "nginx_private - {{ project_name }} - virtualhost.conf - Check REMOTE"
  stat:
    path: "/etc/nginx/sites-available/{{ project_name }}.conf"
  register: remote_virtualconf

- name: "nginx_private - ENDPLAY: virtualhost.conf"
  ansible.builtin.meta: end_play
  when:
  - not local_virtualconf.stat.exists
  - not remote_virtualconf.stat.exists

- name: "nginx_private - {{ project_name }} - Create files folder"
  file:
    path: "/usr/share/nginx/{{ project_name }}"
    state: directory
    owner: "{{ ruser }}"
    group: "www-data"
    mode: '0750'
  become: true

- name: "nginx_private - {{ project_name }} - virtualhost.conf - Copy"
  copy:
    src: "/home/{{ruser}}/mempoule_private/{{ project_name }}/virtualhost.conf"
    dest: "/etc/nginx/sites-available/{{ project_name }}.conf"
    owner: root
    group: root
    mode: '0600'
    force: false
  become: true
  register: copy_virtualconf

- name: "nginx_private - {{ project_name }} - virtualhost.conf - Copy FORCEMODE"
  copy:
    src: "/home/{{ruser}}/mempoule_private/{{ project_name }}/virtualhost.conf"
    dest: "/etc/nginx/sites-available/{{ project_name }}.conf"
    owner: root
    group: root
    mode: '0600'
    force: true
  become: true
  register: copy_virtualconf
  when: force_virtualhost is defined and force_virtualhost

- name: "nginx_private - virtualhost.conf - symbolic link vhost sites-available"
  file:
    src: "/etc/nginx/sites-available/{{ project_name }}.conf"
    dest: "/etc/nginx/sites-enabled/{{ project_name }}.conf"
    state: link
  become: true
  when: not copy_virtualconf.skipped

- name: "nginx - {{ project_name }} - wwwfiles - Get list"
  find:
    paths: "/usr/share/nginx/{{ project_name }}"
  register: current_webfiles

- name: "nginx_private - {{ project_name }} - wwwfiles - Copy"
  copy:
    src: "/home/{{ruser}}/mempoule_private/{{ project_name }}/virtualhost.conf"
    dest: "/usr/share/nginx/{{ project_name }}"
    owner: "{{ ruser }}"
    group: www-data
    mode: '0750'
    force: false
  become: true
  register: copy_wwwfiles

- name: "nginx_private - {{ project_name }} - wwwfiles - Copy FORCEMODE"
  copy:
    src: "/home/{{ruser}}/mempoule_private/{{ project_name }}/virtualhost.conf"
    dest: "/usr/share/nginx/{{ project_name }}"
    owner: "{{ ruser }}"
    group: "{{ ruser }}"
    mode: u=rwX,g=rX,o=
    force: true
  become: true
  register: copy_wwwfiles
  when: force_wwwfiles is defined and force_wwwfiles

- name: "nginx_private - {{ project_name }} - wwwfiles - acl"
  file:
    path: "/usr/share/nginx/{{ project_name }}"
    recurse: yes
    owner: "{{ ruser }}"
    group: "{{ ruser }}"
    mode: u=rwX,g=rX,o=
  become: true
#  when: copy_wwwfiles.changed
