- include_vars:
    file: "vars.json"
    name: var_install

- name: "Install - AdministrativeUser - Check if {{ruser}} is in passwd"
  getent:
    database: passwd
    key: "{{ruser}}"

- name: "Install - AdministrativeUser - Set user_exist var when {{ ruser }} exists"
  set_fact:
    user_exists: true
  when: (ruser in item.key)
  loop: "{{ ansible_facts.getent_passwd | dict2items }}"

- name: "Install - AdministrativeUser - Set user_exist var when {{ ruser }} doesn't exist"
  set_fact:
    user_exists: false
  when: (ruser not in item.key)
  loop: "{{ ansible_facts.getent_passwd | dict2items }}"

- name: "Install - AdministrativeUser - Add user {{ ruser }}"
  user:
    name: "{{ ruser }}"
    shell: /bin/bash
    groups: sudo
    password: "{{ var_install['default_pass'] }}"
  become: true
  when:
    - user_exists is false

- name: Install - AdministrativeUser - .vimrc compatible mode and mouse
  lineinfile:
    dest: "/home/{{ruser}}/.vimrc"
    line: "set nocompatible"
    state: present
    create: true

- name: Install - AdministrativeUser - .vimrc compatible mode and mouse
  lineinfile:
    dest: "/home/{{ruser}}/.vimrc"
    line: "set mouse-=a"
    state: present
    create: true

- name: Install - AdministrativeUser - ll alias in .bashrc
  lineinfile:
    dest: "/home/{{ruser}}/.bashrc"
    regexp: "alias ll"
    line: "alias ll='ls -alF'"
    state: present
    create: true

- name: Install - AdministrativeUser - Default editor
  lineinfile:
    dest: "/home/{{ruser}}/.bashrc"
    regexp: "export EDITOR="
    line: "export EDITOR=vim"
    state: present
    create: true

- name: Install - AdministrativeUser - Create .ssh folder
  file:
    path: "/home/{{ ruser }}/.ssh"
    state: directory
    owner: "{{ ruser }}"
    group: "{{ ruser }}"
    mode: '0700'
  become: true

- name: Install - AdministrativeUser - Get ssh keys from GitHub
  uri:
    url: "https://api.github.com/users/{{ ruser }}/keys"
    method: GET
    return_content: yes
  register: ghkeys

- name: Install - AdministrativeUser - touch authorized_keys
  copy:
    content: ""
    dest: "/home/{{ruser}}/.ssh/authorized_keys"
    force: no
    group: mempoule
    owner: mempoule
    mode: 0600

- name: "Base - AdministrativeUser - Add {{ ruser }} GitHub ssh keys"
  lineinfile:
    path: "/home/{{ ruser }}/.ssh/authorized_keys"
    state: present
    line: "{{ item.key }}\n"
    create: true
    owner: "{{ ruser }}"
    group: "{{ ruser }}"
  when: item.key not in lookup('ansible.builtin.file', '/home/'+ruser+'/.ssh/authorized_keys')
  with_items: "{{ ghkeys.content }}"
  become: true

- name: Install - AdministrativeUser - Ensure GitHub host key known
  lineinfile:
    dest: "/home/{{ ruser }}/.ssh/known_hosts"
    state: present
    line: "{{ lookup('pipe', 'ssh-keyscan -trsa github.com') }}"
    create: true
    owner: "{{ ruser }}"
    group: "{{ ruser }}"
  become: true

- name: Install - AdministrativeUser - chmod .ssh/authorized_keys
  file:
    path:  "/home/{{ ruser }}/.ssh/authorized_keys"
    mode: '0600'
  become: true

- name: Install - SysTweaks - Disable IPv6 with sysctl
  sysctl:
    name: "{{ item }}"
    value: '1'
    state: present
    reload: true
  with_items:
    - net.ipv6.conf.all.disable_ipv6
    - net.ipv6.conf.default.disable_ipv6
    - net.ipv6.conf.lo.disable_ipv6
  become: true
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_major_version != '20'

- name: Install - SysTweaks - IPV6 disable for ubuntu20.x - checking if already in grub conf
  shell: grep -i '^GRUB_CMDLINE_LINUX_DEFAULT=.*.ipv6\.disable=1.*' /etc/default/grub
  failed_when: "grub_ipv6_ubuntu20.rc not in [ 0, 1 ]"
  register: grub_ipv6_ubuntu20
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_major_version == '20'


- name: Install - SysTweaks - IPV6 disable for ubuntu20.x - append to GRUB_CMDLINE_LINUX_DEFAULT
  lineinfile:
    path: /etc/default/grub
    backrefs: yes
    regexp: '(^GRUB_CMDLINE_LINUX_DEFAULT=.*).{1}'
    line: '\1 ipv6.disable=1"'
  become: true
  when: grub_ipv6_ubuntu20.rc | default('') == 1


- name:  Install - SysTweaks - IPV6 disable for ubuntu20.x - grub update
  shell: update-grub
  become: true
  when: grub_ipv6_ubuntu20.rc | default('') == 1

- name: Install - SysTweaks - Install base packages
  apt:
    pkg:
    - net-tools
    - software-properties-common
    - pkg-config
    - libssl-dev
    - jq
    - git
    - htop
    - ntp
    - ntpdate
    - vim
    - fail2ban
    - bc
    - autoconf
    - automake
    - cmake
    - bsdmainutils
    - debconf-utils
    - curl
    - unzip
    - wget
    - clang
    - iptables-persistent
    - screen
    - python3
    - python3-dev
    - python3-pip
  become: true

- name: Install - SysTweaks - systemd-networkd-wait-online disable
  systemd:
    name: systemd-networkd-wait-online
    enabled: no
    masked: yes
  become: true

- name: Install - Fail2ban - Create jail.local
  copy:
    src: /etc/fail2ban/jail.conf
    dest: /etc/fail2ban/jail.local
    remote_src: true
  become: true

- name: Install - Fail2ban - Comment contents of jail.conf in jail.local
  replace:
    path: /etc/fail2ban/jail.local
    regexp: '(.*)'
    replace: '# \1'
  become: true

- name: Install - Fail2ban - Extend whitelist for fail2ban
  community.general.ini_file:
    dest: /etc/fail2ban/jail.conf
    section: DEFAULT
    option: ignoreip
    value: "{{var_install['fail2ban_ignorelist_str']}}"
    mode: '0640'
    create: yes
  become: true

- name: Install - SSHD - PermitRootLogin
  lineinfile:
    dest: "/etc/ssh/sshd_config"
    regexp: "^[#]*PermitRootLogin"
    line: "PermitRootLogin no"
    state: present
  become: true

- name: Install - SSHD - PasswordAuthentication
  lineinfile:
    dest: "/etc/ssh/sshd_config"
    regexp: "^[#]*PasswordAuthentication"
    line: "PasswordAuthentication no"
    state: present
  become: true

- name: Install - SSHD - PubkeyAuthentication
  lineinfile:
    dest: "/etc/ssh/sshd_config"
    regexp: "^[#]*PubkeyAuthentication"
    line: "PubkeyAuthentication yes"
    state: present
  become: true

- name: Install - SSHD - ChallengeResponseAuthentication
  lineinfile:
    dest: "/etc/ssh/sshd_config"
    regexp: "^[#]*ChallengeResponseAuthentication"
    line: "ChallengeResponseAuthentication no"
    state: present
  become: true

- name: Install - Iptables - Set the policy for the INPUT chain to ACCEPT
  iptables:
    chain: INPUT
    policy: ACCEPT
  become: true

- name: Install - Iptables - Set the policy for the FORWARD chain to ACCEPT
  iptables:
    chain: FORWARD
    policy: ACCEPT
  become: true

- name: Install - Iptables - Set the policy for the OUTPUT chain to ACCEPT
  iptables:
    chain: OUTPUT
    policy: ACCEPT
  become: true

- name: Install - Iptables - Allow related and established connections
  iptables:
    chain: INPUT
    ctstate: ESTABLISHED,RELATED
    jump: ACCEPT
  become: true

- name: Install - Iptables - Allow lo
  iptables:
    chain: INPUT
    in_interface: lo
    jump: ACCEPT
  become: true

- name: Install - Iptables - SSH whitelist
  iptables:
    chain: INPUT
    protocol: tcp
    destination_port: '22'
    source: "{{item}}"
    jump: ACCEPT
  loop: "{{var_install['iptables_allowed_ssh']}}"
  become: true

- name: Install - Iptables - Deny else
  iptables:
    chain: INPUT
    jump: DROP
  become: true

- name: Install - Iptables - Save rules
  community.general.iptables_state:
    ip_version: ipv4
    table: filter
    state: saved
    path: /etc/iptables/rules.v4
  become: true

- name: Install - Ansible - Get GPG key
  shell: gpg --homedir /tmp --no-default-keyring --keyring /usr/share/keyrings/ansible.gpg --keyserver keyserver.ubuntu.com --recv-keys 93c4a3fd7bb9c367
  become: true

- name: Install - Ansible - Create the ansible.list - 22-JAMMY
  lineinfile:
      path: /etc/apt/sources.list.d/ppa_ansible_ansible.list
      line: 'deb [arch=amd64 signed-by=/usr/share/keyrings/ansible.gpg] http://ppa.launchpad.net/ansible/ansible/ubuntu jammy main'
  when: is_commander is defined and is_commander and ansible_distribution == 'Ubuntu' and ansible_distribution_version == '22.04'
  become: true

- name: Install - Ansible - Create the ansible.list - 20-JAMMY
  lineinfile:
      path: /etc/apt/sources.list.d/ppa_ansible_ansible.list
      line: 'deb [arch=amd64 signed-by=/usr/share/keyrings/ansible.gpg] http://ppa.launchpad.net/ansible/ansible/ubuntu focal main'
  when: is_commander is defined and is_commander ansible_distribution == 'Ubuntu' and ansible_distribution_version == '20.04'
  become: true

- name: Install - Ansible - Create the ansible.list - 20-JAMMY
  lineinfile:
      path: /etc/apt/sources.list.d/ppa_ansible_ansible.list
      line: 'deb [arch=amd64 signed-by=/usr/share/keyrings/ansible.gpg] http://ppa.launchpad.net/ansible/ansible/ubuntu bionic main'
  when: is_commander is defined and is_commander ansible_distribution == 'Ubuntu' and ansible_distribution_version == '18.04'
  become: true

- name: Install - SysTweaks - Hostname update
  hostname:
    name: "{{ target_hostname }}"
  register: hostname_changed
  when: target_hostname is defined and target_hostname != ansible_fqdn
  become: true

- name: Install - SysTweaks - /etc/hosts update existing entry
  lineinfile:
    state: present
    dest: /etc/hosts
    line: "{{ ansible_default_ipv4.address }} {{ target_hostname }}"
    regexp: "^{{ ansible_default_ipv4.address }}"
  register: hostname_already_present
  when: hostname_changed.changed
  become: true

- name: Install - SysTweaks - /etc/hosts add the entry if not present
  lineinfile:
    state: present
    dest: /etc/hosts
    line: "{{ ansible_default_ipv4.address }} {{ target_hostname }}"
  when: not hostname_already_present.changed
  become: true

- name: Install - SysTweaks - Reboot post Hostname Change
  reboot:
    reboot_timeout: 300
  when: hostname_changed.changed and is_commander is not defined
  become: true

- name: Install - SysTweaks - Waiting machine restart
  wait_for_connection:
    connect_timeout: 60
    sleep: 5
    delay: 5
    timeout: 300
  when: hostname_changed.changed and is_commander is not defined
  become: true


