- hosts: mempoule_commander_adm
  roles:
#    - role: apt
#    - role: install
    - { role: git, git_name: "toolbox_private", url_repo: "https://github.com/mempoule/toolbox_private.git", private_git: True }
  vars:
    ruser: mempoule
