- hosts: piticker
  roles:
    - role: install 
#    - { role: git, git_name: "testpublic", url_repo: "https://github.com/mempoule/testpublic.git" }
#    - { role: iptables, ruleset: piticker }
  vars:
    ruser: mempoule

