- import_tasks: clone_public.yml
  when:
  - type is undefined or type == "clone"
  - git_name is defined
  - url_repo is defined
  - private_git is not defined or
    private_git is defined and not private_git

- import_tasks: clone_private.yml
  when:
  - type is undefined or type == "clone"
  - url_repo is defined
  - git_name is defined
  - private_git is defined and private_git
