- import_tasks: public.yml
  when:
  - url_repo is defined
  - private_git is not defined or
    private_git is defined and not private_git

- import_tasks: private.yml
  when:
  - url_repo is defined
  - private_git is defined and private_git
