- name: "Git - PRIVATE - generate SSH key for {{ git_name }}"
  openssh_keypair:
    path: "~/.ssh/{{ git_name }}"
    type: rsa
    size: 2048
    state: present
    force: no
  become: true
  become_user: "{{ ruser }}"

- name: "Git - PRIVATE - chmod ssh key for {{ git_name }}"
  file:
    path: "/home/{{ ruser }}/.ssh/{{ git_name }}"
    mode: '0600'
  become: true

- name: "Git - PRIVATE - SSH pub to var for {{ git_name }}"
  shell: "cat /home/{{ ruser }}/.ssh/{{ git_name }}"
  register: guestpub
  become: true

- name: "Git - Show the guest pub for {{ git_name }}"
  debug:
    msg: "{{ guestpub.stdout }}"
  become: true

