- name: nginx - Base - Install base package(s)
  apt:
    pkg:
      - nginx
  become: true

- name: nginx - Firewall - Port 80
  iptables:
    chain: INPUT
    protocol: tcp
    destination_port: '80'
    jump: ACCEPT
    action: insert
    rule_num: "1"
  become: true
  when: fw_nohttp is not defined or (fw_nohttp is defined and fw_nohttp)

- name: nginx - Firewall - Port 443
  iptables:
    chain: INPUT
    protocol: tcp
    destination_port: '443'
    jump: ACCEPT
    action: insert
    rule_num: "1"
  become: true
  when: fw_nohttps is not defined or (fw_nohttps is defined and fw_nohttps)

- name: nginx - Firewall - Cloudflare - Port 443
  iptables:
    chain: INPUT
    protocol: tcp
    source: "{{ item }}"
    destination_port: '443'
    jump: ACCEPT
    action: insert
    rule_num: "1"
  with_lines: cat vars/cloudflarev4.cfg
  when: fw_cloudflare is defined and fw_cloudflare
  become: true

- name: nginx - Firewall - Cloudflare - Port 80
  iptables:
    chain: INPUT
    protocol: tcp
    source: "{{ item }}"
    destination_port: '443'
    jump: ACCEPT
    action: insert
    rule_num: "1"
  with_lines: cat vars/cloudflarev4.cfg
  when: fw_cloudflare is defined and fw_cloudflare
  become: true
